### ISSUE TITLE
Icon is way too small

### ISSUE THREAD

**Issue by Human79** [Arch-0/MontereyRealtekIcons#1]
Icon is way too small.
![Screen Shot 2021-06-27 at 10 56 16 PM](https://user-images.githubusercontent.com/84245065/123553804-f200b480-d79a-11eb-9584-c732ce5ff8dd.png)
I can give you the icons I extracted from Big Sur if you want.
I found a archived repo contaning the icons. You can find it [here](https://github.com/ichelash/bigsur).
Regards.

**Comment by Arch-0** [comment]
Thank you. I will look at those icons and update soon. I appreciate it :)

**Comment by Arch-0** [comment]
Again, thanks @Human7900 for the input on the size of the icons. 

I have updated the icons (although they are not 100% the same size as the system icons) and the new install script doesn't require a logout anymore, so it will make things better. 

I didn't use the icons you sent me as they looked sort of weird at the edges and it drove me nuts, but I appreciate it nonetheless.

I will be resizing the icons again this week and be looking on ways to make the icons shift from light to dark mode automatically, although I don't know yet how I will tackle that problem.

**Comment by Human79** [comment]
> new install script doesn't require a logout anymore, so it will make things better.

So it hurts a little less
>I didn't use the icons you sent me as they looked sort of weird at the edges and it drove me nuts, but I appreciate it nonetheless.

Even I don't use it.
>I will be resizing the icons again this week and be looking on ways to make the icons shift from light to dark mode automatically, although I don't know yet how I will tackle that problem.

Really hope you find the solution soon, I am also trying to tackle the same problem.
So I extracted wifi icons from Big Sur (original from the system) attaching them.
[WiFi Icons.zip](https://github.com/Arch-0/MontereyRealtekIcons/files/6723239/WiFi.Icons.zip)

From our reddit conservation:
> I was trying to see just a pixel in the top bar and make the script change the icons based on the color but it required the screen recorder to be opened all the time

Can you share it with me?

**Comment by Arch-0** [comment]
Hey. I just fixed the sizing of the icons and for that reason I will be closing this issue!

> From our reddit conservation:
> 
> I was trying to see just a pixel in the top bar and make the script change the icons based on the color but it required the screen recorder to be opened all the time
> 
> Can you share it with me?

I am sorry, I was just testing things out and don't have the code any longer, it wasn't particularly useful anyways. I am still trying to figure it out and when I do I'll gladly share it here.

Thanks for the help so far!

EDIT: You can contact me through Discord (if you wish to discuss things further) at `#ɥɔɹ∀#0002`
